begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(19);
select ok(public._valid_appearance(public._default_character(1)),'Manifest default is valid');
select ok((select count(*) from public.character_asset_options)>=70,'Generated catalog contains supplied layers and may grow');
select ok(not public._valid_appearance(public._default_character(1)||'{"body":"body.missing"}'),'Unknown body ID refused');
select ok(not public._valid_appearance(public._default_character(1)||'{"face":"outfit.coat"}'),'Known ID in wrong role refused');
select ok(not public._valid_appearance(public._default_character(1)||'{"hairBack":"hair_front.bob.black"}'),'Hair front cannot be saved as back');
select ok(not public._valid_appearance(public._default_character(1)||'{"accessories":["accessories.flower","accessories.flower"]}'),'Duplicate accessory refused');
select ok(not public._valid_appearance(public._default_character(1)||'{"accessories":[null]}'),'Null accessory refused');
select ok(not public._valid_appearance(public._default_character(1)||'{"accessories":["face.smile"]}'),'Wrong accessory role refused');
select ok(not public._valid_appearance(public._default_character(1)||'{"accessories":null}'),'Non-array accessories refused');
select ok(public._valid_appearance(public._default_character(1)||'{"accessories":[],"blush":null}'),'Optional blush/accessories may be absent selections');
select ok(not public._valid_appearance(public._default_character(1)||'{"body":1}'),'Numeric prototype option refused');
select ok(not public._valid_appearance(public._default_character(1)||'{"height":2}'),'Extra config field refused');
select ok(not public._valid_appearance(public._default_character(1)-'outfit'),'Missing role refused');
select ok(not public._valid_appearance('null'),'Null look refused');
select ok(not public._valid_appearance('[]'),'Array look refused');
select ok((select bool_and(relrowsecurity) from pg_class where oid in ('public.character_asset_options'::regclass,'public.character_asset_defaults'::regclass)),'Catalog tables use RLS');
insert into public.character_asset_options(id,role) values('body.future_male','body');
select ok(public._valid_appearance(public._default_character(1)||'{"body":"body.future_male"}'),'Future manifest entry works without validator code changes');
set local role authenticated;
select throws_ok($$insert into public.character_asset_options values('body.injected','body')$$,'42501',null,'Clients cannot extend allowed IDs');
select throws_ok($$update public.character_asset_defaults set appearance='{}'$$,'42501',null,'Clients cannot replace defaults');
reset role;
select * from finish();
rollback;
