import {useEffect,useRef,useState} from 'react';
import {appearanceSchema,characterOptions,characterManifest,optionLabel} from '@paw/shared';
import type {Appearance,CharactersState,CharacterRole} from '@paw/shared';
import {drawPortrait,prepareCharacterArt} from './CharacterArt';
type Props={initial:Appearance;step?:number;presets:CharactersState['presets'];onSave:(a:Appearance)=>Promise<void>;onPreset:(slot:number,a:Appearance)=>Promise<void>;onClose:()=>void};
const steps=['Body','Face/Hair','Clothes','Review'];
export function CharacterEditor({initial,step=0,presets,onSave,onPreset,onClose}:Props){
 const [draft,setDraft]=useState(initial),[page,setPage]=useState(step),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preset,setPreset]=useState(0);
 const canvas=useRef<HTMLCanvasElement>(null),panel=useRef<HTMLElement>(null);
 useEffect(()=>{panel.current?.focus();},[]);
 useEffect(()=>{let cancelled=false;void prepareCharacterArt().then(()=>{if(cancelled)return;const ctx=canvas.current?.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,200,300);drawPortrait(ctx,draft);}).catch(()=>{if(!cancelled)setError('Character art could not load. Please reopen the editor.');});return()=>{cancelled=true;};},[draft]);
 const select=(label:string,key:Exclude<CharacterRole,'accessories'>)=> <label key={key}>{label}<select aria-label={label} value={draft[key]??''} disabled={busy} onChange={e=>setDraft(current=>({...current,[key]:e.target.value||null}))}>{key==='blush'&&<option value="">None</option>}{characterOptions(key).map(option=><option key={option.id} value={option.id}>{optionLabel(option.id)}</option>)}</select></label>;
 const action=async(task:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await task();}catch(e){setError(e instanceof Error?e.message:'Could not save. Try again.');}finally{setBusy(false);}};
 return <div className="character-backdrop"><section className="character-editor" ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Character" onKeyDown={e=>{
  if(e.key==='Escape'&&!busy){onClose();return;}
  if(e.key==='Tab'){const controls=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),select:not(:disabled),input:not(:disabled)'));const first=controls[0],last=controls.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}
 }}><header><h2>Your character</h2><span>{page+1} / 4 · {steps[page]}</span><button disabled={busy} onClick={onClose}>Cancel</button></header><div className="character-editor-body"><div className="character-preview"><canvas ref={canvas} width={200} height={300} aria-label="Character preview" role="img"/><p>{characterManifest.placeholder_labels[0]}</p></div><div className="character-options">
 {page===0&&<>{select('Skin tone','body')}{select('Blush','blush')}<p className="placeholder-note">{characterManifest.placeholder_notes.body}</p></>}
 {page===1&&<>{select('Hair back','hairBack')}{select('Hair front','hairFront')}{select('Face','face')}<p className="placeholder-note">{characterManifest.placeholder_notes.face}</p></>}
 {page===2&&<>{select('Outfit','outfit')}<fieldset><legend>Accessories</legend>{characterOptions('accessories').map(option=><label key={option.id}><input type="checkbox" disabled={busy} checked={draft.accessories.includes(option.id)} onChange={e=>setDraft(current=>({...current,accessories:e.target.checked?[...current.accessories,option.id]:current.accessories.filter(id=>id!==option.id)}))}/>{optionLabel(option.id)}</label>)}</fieldset><p className="placeholder-note">{characterManifest.placeholder_notes.clothes}</p><fieldset><legend>Outfits</legend><label>Outfit slot<select value={preset} disabled={busy} onChange={e=>setPreset(Number(e.target.value))}>{[0,1,2,3,4].map(slot=><option key={slot} value={slot}>Outfit {slot+1}</option>)}</select></label><div className="actions"><button disabled={busy||!presets.some(p=>p.slot===preset)} onClick={()=>{const saved=presets.find(p=>p.slot===preset)!;setDraft(current=>({...current,outfit:saved.appearance.outfit,accessories:[...saved.appearance.accessories]}));}}>Wear</button><button disabled={busy} onClick={()=>void action(()=>onPreset(preset,appearanceSchema.parse(draft)))}>Save outfit</button></div></fieldset></>}
 {page===3&&<><h3>Ready to move in?</h3><p>{optionLabel(draft.body)} · {optionLabel(draft.outfit)}</p><p>Your partner will see your saved look. You can change it later at a mirror or wardrobe.</p><p className="placeholder-note">{characterManifest.placeholder_notes.review}</p></>}
 </div></div><footer><p role="alert">{error}</p><div className="actions">{page>0&&<button disabled={busy} onClick={()=>setPage(page-1)}>Back</button>}{page<3?<button disabled={busy} onClick={()=>setPage(page+1)}>Next</button>:<button disabled={busy} onClick={()=>void action(()=>onSave(appearanceSchema.parse(draft)))}>{busy?'Saving…':'Save'}</button>}</div></footer></section></div>;
}
