import {useEffect,useRef,useState} from 'react';
import {appearanceSchema,skinTones,characterColors,hairNames} from '@paw/shared';
import type {Appearance,CharactersState} from '@paw/shared';
import {drawCharacter} from './CharacterArt';
type Props={initial:Appearance;step?:number;presets:CharactersState['presets'];onSave:(a:Appearance)=>Promise<void>;onPreset:(slot:number,a:Appearance)=>Promise<void>;onClose:()=>void};
const steps=['Body','Face/Hair','Clothes','Review'];
export function CharacterEditor({initial,step=0,presets,onSave,onPreset,onClose}:Props){
 const [draft,setDraft]=useState(initial),[page,setPage]=useState(step),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preset,setPreset]=useState(0);
 const canvas=useRef<HTMLCanvasElement>(null),panel=useRef<HTMLElement>(null);
 useEffect(()=>{panel.current?.focus();},[]);
 useEffect(()=>{const ctx=canvas.current?.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,192,256);ctx.save();ctx.scale(2,2);for(const layer of ['base','pants','shirt','shoes','glasses'] as const)drawCharacter(ctx,draft,layer);ctx.restore();},[draft]);
 const update=(key:keyof Appearance,value:number)=>setDraft(current=>({...current,[key]:value}));
 const select=(label:string,key:keyof Appearance,options:readonly string[])=> <label key={key}>{label}<select aria-label={label} value={draft[key]} disabled={busy} onChange={e=>update(key,Number(e.target.value))}>{options.map((name,i)=><option key={name} value={i}>{name}</option>)}</select></label>;
 const colors=(label:string,key:keyof Appearance,palette:readonly string[])=> <fieldset key={key}><legend>{label}</legend><div className="character-swatches">{palette.map((color,i)=><button type="button" key={color} aria-label={`${label} ${i+1}`} aria-pressed={draft[key]===i} style={{backgroundColor:color}} disabled={busy} onClick={()=>update(key,i)}>{draft[key]===i?'✓':''}</button>)}</div></fieldset>;
 const action=async(task:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await task();}catch(e){setError(e instanceof Error?e.message:'Could not save. Try again.');}finally{setBusy(false);}};
 return <div className="character-backdrop"><section className="character-editor" ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Character" onKeyDown={e=>{
  if(e.key==='Escape'&&!busy){onClose();return;}
  if(e.key==='Tab'){const controls=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),select:not(:disabled)'));const first=controls[0],last=controls.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}
 }}><header><h2>Your character</h2><span>{page+1} / 4 · {steps[page]}</span><button disabled={busy} onClick={onClose}>Cancel</button></header><div className="character-editor-body"><div className="character-preview"><canvas ref={canvas} width={192} height={256} aria-label="Character preview" role="img"/><p>Make yourself at home.</p></div><div className="character-options">
 {page===0&&<>{colors('Skin tone','skin',skinTones)}{select('Body','body',['Slim','Soft','Broad'])}{select('Height','height',['Small','Medium','Tall'])}</>}
 {page===1&&<>{select('Hair','hair',hairNames)}{colors('Hair color','hairColor',characterColors)}{select('Eyes','eyes',['Bright','Round','Gentle','Lashes','Sleepy','Bold'])}{select('Mouth','mouth',['Smile','Grin','Small','Soft'])}{select('Glasses','glasses',['None','Round','Square'])}</>}
 {page===2&&<>{select('Shirt','shirt',['T-shirt','Hoodie','Stripes'])}{colors('Shirt color','shirtColor',characterColors)}{select('Pants','pants',['Trousers','Shorts','Soft pants'])}{colors('Pants color','pantsColor',characterColors)}{select('Shoes','shoes',['Slip-ons','Sneakers','Boots'])}{colors('Shoes color','shoesColor',characterColors)}<fieldset><legend>Outfits</legend><label>Outfit slot<select value={preset} onChange={e=>setPreset(Number(e.target.value))}>{[0,1,2,3,4].map(slot=><option key={slot} value={slot}>Outfit {slot+1}</option>)}</select></label><div className="actions"><button disabled={busy||!presets.some(p=>p.slot===preset)} onClick={()=>{const saved=presets.find(p=>p.slot===preset)!;setDraft(current=>({...current,...Object.fromEntries(['shirt','shirtColor','pants','pantsColor','shoes','shoesColor','glasses'].map(key=>[key,saved.appearance[key as keyof Appearance]]))}));}}>Wear</button><button disabled={busy} onClick={()=>void action(()=>onPreset(preset,appearanceSchema.parse(draft)))}>Save outfit</button></div></fieldset></>}
 {page===3&&<><h3>Ready to move in?</h3><p>{['Slim','Soft','Broad'][draft.body]} · {['Small','Medium','Tall'][draft.height]} · {hairNames[draft.hair]}</p><p>Your partner will see your saved look. You can change it later at a mirror or wardrobe.</p></>}
 </div></div><footer><p role="alert">{error}</p><div className="actions">{page>0&&<button disabled={busy} onClick={()=>setPage(page-1)}>Back</button>}{page<3?<button disabled={busy} onClick={()=>setPage(page+1)}>Next</button>:<button disabled={busy} onClick={()=>void action(()=>onSave(appearanceSchema.parse(draft)))}>{busy?'Saving…':'Save'}</button>}</div></footer></section></div>;
}
