import {z} from 'zod';
import manifest from '../../../assets/characters/chibi_v1/manifest.json' with {type:'json'};
export const characterManifest=manifest;
export type CharacterRole='body'|'blush'|'hairBack'|'hairFront'|'face'|'outfit'|'accessories';
export const characterOptions=(role:CharacterRole)=>manifest.layers.filter(l=>role==='body'?l.group==='body'&&!l.sub.includes('blush'):role==='blush'?l.group==='body'&&l.sub.includes('blush'):l.group===({hairBack:'hair_back',hairFront:'hair_front'} as Record<string,string>)[role]||l.group===role);
export const optionLabel=(id:string)=>id.split('.').slice(1).join(' · ').replaceAll('_',' ');
const option=(role:CharacterRole)=>z.string().refine(id=>characterOptions(role).some(l=>l.id===id),`Unknown ${role} option`);
export const appearanceSchema=z.object({body:option('body'),blush:option('blush').nullable(),hairBack:option('hairBack'),hairFront:option('hairFront'),face:option('face'),outfit:option('outfit'),accessories:z.array(option('accessories')).max(5).refine(ids=>new Set(ids).size===ids.length,'Duplicate accessories')}).strict();
export type Appearance=z.infer<typeof appearanceSchema>;
export const defaultAppearance=(_seat=1):Appearance=>appearanceSchema.parse(structuredClone(manifest.default_config));
const index=(max:number)=>z.number().int().min(0).max(max);
export const emotes=['love','hug','wave','laugh','cry','angry','please','clap','dance','yawn','kiss'] as const;
export type Emote=typeof emotes[number];
export const emoteIcons:Record<Emote,string>={love:'❤️',hug:'🫂',wave:'👋',laugh:'😂',cry:'😭',angry:'😡',please:'🥺',clap:'👏',dance:'💃',yawn:'😴',kiss:'😘'};
export const emoteSchema=z.object({couple_id:z.uuid(),user_id:z.uuid(),session_id:z.uuid(),request_id:z.uuid(),emote:z.enum(emotes)}).strict();
export const socialSchema=z.object({id:z.uuid(),kind:z.enum(['hug','cuddle']),status:z.enum(['pending','active']),sender_id:z.uuid(),recipient_id:z.uuid(),sender_session:z.uuid(),recipient_session:z.uuid().nullable(),object_id:z.enum(['sofa','bed']).nullable(),sender_x:z.number().finite(),sender_y:z.number().finite(),recipient_x:z.number().finite().nullable(),recipient_y:z.number().finite().nullable(),started_at:z.iso.datetime({offset:true}).nullable(),expires_at:z.iso.datetime({offset:true})}).strict();
export type SocialAction=z.infer<typeof socialSchema>;
export const charactersSchema=z.object({couple_id:z.uuid(),server_time:z.iso.datetime({offset:true}),profiles:z.array(z.object({user_id:z.uuid(),configured:z.boolean(),appearance:appearanceSchema}).strict()).min(1).max(2),presets:z.array(z.object({slot:index(4),appearance:appearanceSchema}).strict()).max(5),social:socialSchema.nullable()}).strict();
export type CharactersState=z.infer<typeof charactersSchema>;
export const characterResultSchema=z.object({ok:z.boolean(),code:z.string().optional()}).strict();
